spring.application.name=aurora

server.port=${PORT:8080}
# ===============================
# CONFIGURACION DE LA BASE DE DATOS NEON
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACION DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACION DE AUTH0 (SECURITY)
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://aurorajk.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://apiaurora
api.zuplo.secret=${ZUPLO_SECRET} 

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG