spring.application.name=aurora

# ===============================
# CONFIGURACIÓN DE LA BASE DE DATOS NEON
# ===============================
# La URL ahora termina en el nombre de la base de datos
spring.datasource.url=jdbc:postgresql://ep-autumn-hill-a42kv268-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require

# Sacamos el usuario y contraseña de la URL y los ponemos aquí:
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oUwN54jnJEbK

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logueo de SQL para ver qué hace Spring por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true