name: OWASP ZAP Security Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Escaneo de vulnerabilidades
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://aurora-backend-bqn9.onrender.com'
          token: ${{ secrets.GITHUB_TOKEN }}
          create_issue: false
          fail_action: false

      - name: Subir Reporte de Vulnerabilidades
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-security-report
          path: zap_report.html